# Generated by Django 4.2.6 on 2023-11-27 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bank_operations', '0004_card'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=2, max_digits=2)),
                ('value_fees', models.DecimalField(decimal_places=2, max_digits=2)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('fee', models.DecimalField(decimal_places=2, max_digits=2)),
                ('expiration', models.DateField()),
                ('condition', models.CharField(choices=[('A', 'Approved'), ('D', 'Denied'), ('P', 'Paying'), ('W', 'Waiting')], default='W', max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Loan', to='bank_operations.account')),
            ],
        ),
    ]
