# Generated by Django 4.2.6 on 2023-11-27 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_operations', '0006_alter_loan_value_alter_loan_value_fees'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='fee',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
