# Generated by Django 4.2.6 on 2023-11-27 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_operations', '0007_alter_loan_fee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='condition',
            field=models.CharField(choices=[('W', 'Waiting'), ('A', 'Approved'), ('D', 'Denied'), ('P', 'Paying')], default='W', max_length=1),
        ),
        migrations.AlterField(
            model_name='loan',
            name='fee',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='loan',
            name='value',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
        migrations.AlterField(
            model_name='loan',
            name='value_fees',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
