# Generated by Django 4.2.6 on 2023-11-27 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_operations', '0008_alter_loan_condition_alter_loan_fee_alter_loan_value_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='fee',
            field=models.IntegerField(max_length=2),
        ),
        migrations.AlterField(
            model_name='loan',
            name='value_fees',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
    ]
