# Generated by Django 4.2.6 on 2023-11-27 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_operations', '0009_alter_loan_fee_alter_loan_value_fees'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='fee',
            field=models.IntegerField(),
        ),
    ]
