# Generated by Django 4.2.6 on 2023-11-28 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_operations', '0010_alter_loan_fee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='state',
            field=models.CharField(choices=[('B', 'Blocked'), ('A', 'Active')], default='B', max_length=1),
        ),
    ]
