version: '3.8'

services:
  api:
    build: .
    command: >
      sh -c "python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/bank-api
    ports:
      - "8000:8000"
    environment:
    - DB_PORT=5432
    - DB_USERNAME=api_posts
    - DB_USER=dev
    - DB_PASSWORD=12345678
    - DB_HOST=db

  db:
    image: postgres:alpine
    volumes:
      - postgres_db:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=dev
      - POSTGRES_PASSWORD=12345678
      - POSTGRES_DB=api_posts
    ports:
      - 8006:5432

volumes:
  postgres_db:
